[tool.poetry]
poetry-mode=false

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^3.11.0"
email-validator = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
